server:
  port: 1001

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 1111

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:1111@localhost1:1002/eureka
  instance:
    hostname: localhost
  server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000